### ISSUE TITLE
Implement /party help function.

### ISSUE THREAD

**Issue by JaydenLyte** [JaydenLyte/Parties#100]
It will show what each command does:
`/party invite PlayerName` invites the player to a party. Can only be done by the leader. Other player must not be in a party. Party cannot exceed partyConfig players.
`/party accept` accepts the last invite you received.
`/party decline` declines the last invite you received. 
`/party kick PlayerName` removes the player from the party. Can only be done by the leader.
`/party leave` leaves the current party.
`/party leader PlayerName` transfers party ownership to a new player.
`/party reload` reloads the dimension configurations and default preset configurations. they are found under /config/sedparties/dims/ and /defaultconfigs/presets/ respectively.
`/party help ArgumentName` shows specific information on a following command: current arguments supported: `invite, accept, decline, kick, leave,l eader, reload`

**Comment by EtherealOnyx** [comment]
Going the route listed in #182 instead.
