### ISSUE TITLE
Suggestion: Support for FTB Teams

### ISSUE THREAD

**Issue by YaibaToKen** [JaydenLyte/Parties#194]

**Comment by JaydenLyte** [comment]
It'l come soon. When I add it it will be similar to the vanilla team system I added, where it creates the teams automatically. On party disband, though, it would get rid of them too.

**Comment by JaydenLyte** [comment]
Support has been added in p4 [here.](https://www.curseforge.com/minecraft/mc-mods/parties/files/5719431l)

If enabled in the config, party management will be done through FTB Teams completely, and no party commands will work.
