### ISSUE TITLE
Suggestion: Support for Everlasting Abilities

### ISSUE THREAD

**Issue by YaibaToKen** [JaydenLyte/Parties#195]

**Comment by JaydenLyte** [comment]
What do you want supported from it?

If I recall correctly, Everlasting Abilities has support for vanilla teams already. The mod can create, modify, and remove vanilla teams automatically.

**Comment by YaibaToKen** [comment]
Apologies, I was in a bit of a rush and didn't even realise that the mod would work out of the box, thank you
